# This is a config for E2B sandbox template.
# You can use template ID (0ngk6u08p3kozbveoos3) or template name (vibe-nextjs-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test')

team_id = "8a875079-a8ee-4ec0-bb17-d6f56faad9b7"
start_cmd = "compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test"
template_id = "0ngk6u08p3kozbveoos3"
